<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.537">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>pap</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="pap_files/libs/clipboard/clipboard.min.js"></script>
<script src="pap_files/libs/quarto-html/quarto.js"></script>
<script src="pap_files/libs/quarto-html/popper.min.js"></script>
<script src="pap_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="pap_files/libs/quarto-html/anchor.min.js"></script>
<link href="pap_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pap_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="pap_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="pap_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="pap_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<section id="utilization-of-cervical-cancer-screening-by-cytology-and-the-burden-of-epithelial-abnormalities-a-tertiary-center-42-years-study" class="level1">
<h1>Utilization of cervical cancer screening by cytology and the burden of epithelial abnormalities: A tertiary-center 42-years study</h1>
<section id="early-cervical-cancer-detection-collaborators" class="level2">
<h2 class="anchored" data-anchor-id="early-cervical-cancer-detection-collaborators">Early Cervical Cancer Detection Collaborators</h2>
<p>Department of Obstetrics and Gynecology, Faculty of Medicine, Ain Shams University</p>
</section>
<section id="corresponding-author" class="level2">
<h2 class="anchored" data-anchor-id="corresponding-author">Corresponding author</h2>
<p>Radwa Ali</p>
<p>Address: Department of Obstetrics and Gynecology, Faculty of Medicine, Ain Shams University, Abbassia, 11566, Cairo, Egypt</p>
<p>Email:</p>
<p>ORCID</p>
</section>
</section>
<section id="abstract" class="level1">
<h1>Abstract</h1>
<p>Background: cytological screening is a high impact practice for reducing cervical cancer incidence and mortality. While few studies examined the efforts to decrease cervical cancer’s burden in Egypt, no study has reported the temporal trends in cervical cancer screening practice and burden of epithelial abnormalities. We sought to fill this knowledge gap by identifying trends in screening practice and the prevalence of epithelial abnormalities.</p>
<p>Methods: Routine healthcare data were collected from March 1981 to December 2022, at the Early Cancer Detection Unit, Ain Shams University Hospital in Egypt. Cervical smear was obtained using a standardized technique and sent to the cytopathology laboratory for conventional cytology examination. The results of the examined smears were reported according to The Bethesda System for Reporting Cervical Cytology. Data were analyzed to describe the trend of in the number of women screened each year and the prevalence of epithelial abnormalities in this period.</p>
<p>Results: The results included data from 95120 women whose smears were satisfactory. The mean age of women at the time of screening was 38.5 (10.5). Abnormal epithelial cells were reported in 5174 women (5.44%). Of these epithelial abnormalities, the majority were low grade squamous intraepithelial lesions in 4144 women (4.36%). Other abnormalities included ASC in 378 women (0.40%), HGSIL in 226 women (0.24%), AG cells NOS in 184 women (0.19%). adenocarcinoma in 165 women (0.17%), malignant SCC in 70 women (0.07%), and AG cells favor neoplastic in 7 women (0.01%). Women with an early age at first intercourse, who opted for routine cervical cytology screening, and who were older at screening were more likely to have epithelial abnormalities. The yearly number of screened women was positively associated with the observed LGSIL (correlation coefficient [95%CI] = 0.8402 [0.7201, 0.9114]), not significantly associated with HGSIL (correlation coefficient [95%CI] = 0.2608 [-0.0468, 0.5233]), and negatively associated with the observed suspected invasion (correlation coefficient [95%CI] = -0.5483 [-0.7305, -0.2933]).</p>
<p>Conclusions: The trend in cervical cytology is associated with an increase in low grade squamous intraepithelial lesions and a decline of suspected invasive lesions. The number of yearly screened women remains extremely small. Action is needed to scale up and sustain cervical cancer screening.&nbsp;</p>
</section>
<section id="keywords" class="level1">
<h1>Keywords</h1>
<p>Early Detection of Cancer, Cancer Screening, Uterine Cervical Neoplasms, Cervical cancer, Squamous Intraepithelial Lesions of the Cervix</p>
</section>
<section id="background" class="level1">
<h1>Background</h1>
<p>Cervical cancer, a matter of public health concern, is ranked as the fourth most prevalent form of cancer in women worldwide. In the context of Egypt, it is the 14th most commonly occurring cancer among women. <span class="citation" data-cites="ferlay2020">[<a href="#ref-ferlay2020" role="doc-biblioref">1</a>]</span></p>
<p>The natural history of cervical cancer has been extensively documented. There is widespread acceptance of a multi-step carcinogenesis model, wherein the critical stages are HPV infection, progression to pre-cancerous state, and subsequent development of invasive cancer. <span class="citation" data-cites="Schiffman2016 Wright2023">[<a href="#ref-Schiffman2016" role="doc-biblioref">2</a>,<a href="#ref-Wright2023" role="doc-biblioref">3</a>]</span></p>
<p>Cervical cancer is largely preventable, and there has been a decline in its incidence over the past few decades in most countries, although the extent of this reduction varies. This decline can be attributed to both vaccination and screening for precursor lesions, followed by appropriate follow-up and treatment. <span class="citation" data-cites="Bouvard2021 WHO2021">[<a href="#ref-Bouvard2021" role="doc-biblioref">4</a>,<a href="#ref-WHO2021" role="doc-biblioref">5</a>]</span> This has formed the foundation for the World Health Organization (WHO) global initiative to eliminate cervical cancer as a public health problem. One cornerstone of this initiative is achieving a target of 70% screening coverage of women aged 30–49 years with a high-performance test. <span class="citation" data-cites="wh2020">[<a href="#ref-wh2020" role="doc-biblioref">6</a>]</span></p>
<p>A screening program is the initial mandatory step of a process, specifically screening, triage of individuals with positive screening results, confirmation through biopsy, and treatment of individuals with precancerous lesions. <span class="citation" data-cites="Bouvard2021">[<a href="#ref-Bouvard2021" role="doc-biblioref">4</a>]</span></p>
<p>Screening is available in many countries through either population-based (organized) or non-population-based (unorganized) programs, as well as through opportunistic screening. Participation rates and coverage vary significantly across countries and settings. The key factors influencing participation are socioeconomic status, health insurance coverage, public awareness, and level of education. Additionally, some women may face barriers to accessing these services due to a lack of power, authority, or control, which can be major obstacles to their participation. <span class="citation" data-cites="Gakidou2008 Peirson2013 Perkins2023">[<a href="#ref-Gakidou2008" role="doc-biblioref">7</a>–<a href="#ref-Perkins2023" role="doc-biblioref">9</a>]</span></p>
<p>According to the 2015 Egypt Health Issues Survey, the knowledge and utilization of pap smears for cervical cancer screening among women is quite limited. Only 7 percent of women between the ages of 15 and 59 had ever heard of a pap smear, and a very small percentage (0.3 percent) had actually undergone the procedure. The proportion of women who were aware of pap smears exceeded 10 percent only among women residing in urban governorates (14 percent), women working for cash (13 percent), and women in the highest wealth quintile (11 percent). In all subgroups, one percent or less of women reported ever having had a pap smear. <span class="citation" data-cites="Health2015">[<a href="#ref-Health2015" role="doc-biblioref">10</a>]</span></p>
<p>Given the limited knowledge and low utilization of cervical screening among Egyptian women, coupled with the absence of a well-established and sustained population-based screening program, there is a lack of comprehensive understanding regarding the trends of epithelial abnormalities in cervical cytology within the largest population in Africa and the Middle East. Previous research has not thoroughly investigated the outcomes of cervical cancer screening among Egyptian women and how they evolve over time. Therefore, our objective is to examine the temporal trends in cervical cytology practice and the observed epithelial abnormalities.</p>
</section>
<section id="methods" class="level1">
<h1>Methods</h1>
<p>This observational study used routinely collected health data from the Early Cancer Detection Unit (ECDU) following Institutional Review Board approval from the Department of Obstetrics and Gynecology, Ain Shams University, Cairo, Egypt. Informed consent from participants was not collected as all analyses were conducted using de-identified data collected in the process of healthcare administration at the University Hospital.</p>
<section id="study-population-and-data-source" class="level2">
<h2 class="anchored" data-anchor-id="study-population-and-data-source">Study Population and Data Source</h2>
<p>ECDU began opportunistic screening and treatment for cervical cancer in March 1981. ECDU provides the service at a subsidized cost that is much cheaper than women would find at other healthcare facilities in Egypt. Participants included all adult women who did not have any prior screening in 10 years and who underwent conventional cervical screening in the ECDU from March 1981 to December 2022.</p>
<p>No formal referral process exists between healthcare facilities in Egypt. However, the resources available at ECDU for the detection and treatment of cervical cancer make obtaining screening at ECDU an essential step in the continuum of cancer prevention and control within the country. As a result, many women are referred to ECDU from public or private healthcare facilities across Egypt to obtain a pap smear, to obtain follow-up evaluations after a suspicious screening using other methods such as visual inspection aided by acetic acid or Lugol’s iodine, or to begin the process of cancer treatment. ECDU does not employ a systematic method of recruiting women to undergo cervical cancer screening, therefore, the women either self-referred or were referred by a healthcare provider for screening. Data identifying the source of referral for screening as the individual or a healthcare provider were not captured in this dataset. According to ECDU institutional practice, women who have low-grade infections at the time of a pap smear are screened again within 6 months of the prior visit, indicating that women often had multiple screening visits.</p>
<p>The ECDU started to use an electronic database in 1986, in addition to paper records, to capture relevant demographics (i.e.&nbsp;age, address, marital status, number of pregnancies), risk factors for cervical cancer (i.e.&nbsp;previous sexually transmitted infections, parity, oral contraceptive use), and clinical outcomes (outcomes of pap smear) of women who were screened at the clinic. At the first pap smear, a unique identifying number that was used to update each woman’s record. The database has been maintained since its inception, making it an excellent source of longitudinal data to examine trends in cervical cancer screening in a tertiary university healthcare facility in Egypt. All paper records, prior to the establishment of the electronic record system, were transcribed into the database.</p>
<p>Cervical cytology (Pap smear) was obtained using an Ayer’s spatula and spread over a marked glass slide, which was placed in 95% ethyl alcohol and sent to the cytopathology laboratory for conventional cytology examination. Data were recorded using a structured form. The results of the examined smears were reported according to The Bethesda System for Reporting Cervical Cytology. The terminology of CIN1, 2, and 3 was used in the ECDU till 2004. Following the adoption of the Bethesda system, the ECDU transformed all data to match the new system terminology.</p>
</section>
<section id="data-analyses" class="level2">
<h2 class="anchored" data-anchor-id="data-analyses">Data analyses</h2>
<p>ECDU provided a de-identified dataset spanning a 42-year period. We used this dataset to describe clinical and demographic characteristics of screened women, to examine longitudinal trends in screening utilization, and to report the trends of epithelial abnormalities.</p>
<p>Epithelial abnormalities captured at screening were categorized into normal results, low-grade abnormalities (Atypical Squamous Cells of Undetermined Significance or AS-CUS, and Low-grade Squamous Intraepithelial Lesion or LSIL classifications), and high-grade abnormalities (Atypical Squamous Cells, High-grade Lesion or ASC-H, Atypical Glandular Cells or AGUS, High-grade Squamous Intraepithelial Lesion or HSIL, and Invasive cancer).</p>
<p>We conducted analyses summarizing patient characteristics including age at screening, parity, reporting means and standard deviations. We also assessed marital status, and pap smear outcome by Bethesda classification system as categorical variables, reporting proportions for each variable. The primary outcome of interest was the number of pap smears completed by year, including the cytological results of those screenings.</p>
<p>Data were analyzed using the Statistical Package for the Social Science (SPSS), Version 20 (IBM Corp., Armonk, USA).</p>
</section>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>In a period of 42 years from March 1981 to December 2022, 100155 Pap smears were collected from women attending the ECDU, at the Department of Obstetrics and Gynecology, Ain Shams University, Cairo, Egypt. Following data cleaning, 95120 smears were available for data analysis.</p>
<p>The mean age of the women screened was 38.48 (10.45). Most of women were married and were examined as a routine check-up, <a href="#tbl-demogr" class="quarto-xref">Table&nbsp;1</a>. Among women who opted for screening due to clinical symptoms, vaginal discharge (26%) was the commonest indication. The majority of smears (57072/95120 [60.00%]) were performed following referral from a healthcare provider to the ECDU for screening.</p>
<div id="tbl-demogr" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-demogr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Demographic characteristics of women screened at ECDU, Ain Shams University, 1981– 2022
</figcaption>
<div aria-describedby="tbl-demogr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<colgroup>
<col style="width: 44%">
<col style="width: 29%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th>Demographic and clinical characteristics</th>
<th>Mean (SD) or number (%)</th>
<th>Valid number</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Age at screening (years)</td>
<td>38.48 (10.45)</td>
<td>95120</td>
</tr>
<tr class="even">
<td>Age at first intercourse (years)</td>
<td>20.05 (1.39)</td>
<td>89490</td>
</tr>
<tr class="odd">
<td>Marital status</td>
<td></td>
<td>95120</td>
</tr>
<tr class="even">
<td>Married</td>
<td>93709 (98.52)</td>
<td></td>
</tr>
<tr class="odd">
<td>Separated</td>
<td>86 (0.09)</td>
<td></td>
</tr>
<tr class="even">
<td>Widow</td>
<td>819 (0.86)</td>
<td></td>
</tr>
<tr class="odd">
<td>Divorced</td>
<td>506 (0.53)</td>
<td></td>
</tr>
<tr class="even">
<td>Indication for screening</td>
<td></td>
<td>95120</td>
</tr>
<tr class="odd">
<td>Routine asymptomatic</td>
<td>11414 (12.00)</td>
<td></td>
</tr>
<tr class="even">
<td>Symptomatic</td>
<td>30352 (31.91)</td>
<td></td>
</tr>
<tr class="odd">
<td>Not reported</td>
<td>53354 (56.09)</td>
<td></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The temporal trend of screening is depicted in <a href="#fig-scrtrend" class="quarto-xref">Figure&nbsp;1</a>. The median [IQR] number of women who had cervical cytology screening was 1982 [1674, 2928].</p>
<div id="fig-scrtrend" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scrtrend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/trendscreen.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scrtrend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Temporal trend of the number of screened women by year at ECDU, Ain Shams University, 1981– 2022
</figcaption>
</figure>
</div>
<p>Epithelial abnormalities were absent in 94.56% of women (89946/95120; either with or without inflammatory cells 71971 and 17975 respectively), <a href="#tbl-screened" class="quarto-xref">Table&nbsp;2</a></p>
<div id="tbl-screened" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-screened-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Results of cervical cytology among women screened at ECDU, Ain Shams University, 1981– 2022
</figcaption>
<div aria-describedby="tbl-screened-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table">
<thead>
<tr class="header">
<th style="text-align: left;">Finding</th>
<th style="text-align: left;">Frequency</th>
<th style="text-align: left;">Relative frequency</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">NILM</td>
<td style="text-align: left;">89946</td>
<td style="text-align: left;">94.56%</td>
</tr>
<tr class="even">
<td style="text-align: left;">LGSIL</td>
<td style="text-align: left;">4144</td>
<td style="text-align: left;">4.36%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">ASC</td>
<td style="text-align: left;">378</td>
<td style="text-align: left;">0.40%</td>
</tr>
<tr class="even">
<td style="text-align: left;">HGSIL</td>
<td style="text-align: left;">226</td>
<td style="text-align: left;">0.24%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">AG cells NOS</td>
<td style="text-align: left;">184</td>
<td style="text-align: left;">0.19%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Adenocarcinoma</td>
<td style="text-align: left;">165</td>
<td style="text-align: left;">0.17%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Malignant SCC</td>
<td style="text-align: left;">70</td>
<td style="text-align: left;">0.07%</td>
</tr>
<tr class="even">
<td style="text-align: left;">AG cells favor neoplastic</td>
<td style="text-align: left;">7</td>
<td style="text-align: left;">0.01%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">95120</td>
<td style="text-align: left;">100.00%</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Pap smears showed epithelial abnormalities in 5.44% of participants (5174/95120). Epithelial cell abnormalities included LGSIL (low grade squamous intraepithelial lesion) in 4144 women (4.36%) (condyloma in 3113 (3.27%) and CIN I in 1031 (1.08%) women), Atypical squamous cells (ASC) 378 (0.40) (ASCUS in 351 (0.37%) and ASC-H in 27 (0.03%) women), HGSIL (high grade squamous intra-epithelial lesion) in 226 (0.24%) (HGSIL-CIN II in 202 and HGSIL-CIN III in 24 women), and squamous cell carcinoma in 70 (0.07%) women. There were 184 women (0.19%) with Atypical glandular Not Otherwise Specified and 165 women (0.17%) with adenocarcinoma (malignant endocervical cells in 155 and malignant endometrial cells in 10 women).</p>
<p>In the period from 1981 to 2004, condyloma declined from 4% to 1% and CIN I from 9% to 0.52%. Detection of LGSIL declined from 6.9% in 1981 to 4.3% in 2022, while HGSIL declined from 1.2% to 0.13%. Preinvasive lesions (ASC, LGSIL, and HGSIL) declined from 10% in 1981 to 5% in 2022. The temporal trends are depicted in <a href="#fig-sil" class="quarto-xref">Figure&nbsp;2</a> and <a href="#fig-malig" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div id="fig-sil" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sil-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/trendsil.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sil-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Temporal trend of squamous intraepithelial lesion by year among women screened at ECDU, Ain Shams University, 1981– 2022
</figcaption>
</figure>
</div>
<div id="fig-malig" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-malig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/trendmalig.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-malig-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Temporal trend of premalignant and malignant findings by year among women screened at ECDU, Ain Shams University, 1981– 2022
</figcaption>
</figure>
</div>
<p>Patients with abnormal cells showed significantly higher mean age when compared to those with normal cells (40.5 versus 38.4) P &lt;0.001. ASC cases showed significantly older age when compared to LSIL and younger age than HSIL, and Glandular cells (Favor neoplastic) cases P &lt;0.001. LSIL cases showed significantly lower mean age than other abnormal cell cases P &lt;0.001. LGSIL and AGUS showed significant lower age than Malignant Squamous Cell Carcinoma, HSIL and adenocarcinoma cases P &lt;0.05. There was a statistical significant difference between rate of abnormal cells in different age groups P&lt;0.001. The majority of abnormal cells were found among age group above 60, there was statistical significant difference between each pair of age groups except between groups aged &lt; 20 and from 21-30 years, and between groups aged 51-60 and &gt;60 years. Although rates increased along age groups; rates flattened in the middle age groups and appeared to increase in the older age groups.</p>
<p>Epithelial abnormalities were significantly higher in women with routine check-up when compared to symptomatic women (OR [95% CI] 1.2 [1.11, 1.30], P&lt;0.001). Women with epithelial abnormalities had a significantly younger age at first intercourse (P&lt;0.001).</p>
<p>The yearly number of screened women was positively associated with the observed LGSIL (correlation coefficient [95%CI] = 0.8402 [0.7201, 0.9114]) ( <a href="#fig-lg" class="quarto-xref">Figure&nbsp;4</a> ), not significantly associated with HGSIL (correlation coefficient [95%CI] = 0.2608 [-0.0468, 0.5233]) ( <a href="#fig-hg" class="quarto-xref">Figure&nbsp;5</a> ), and negatively associated with the observed suspected invasion (correlation coefficient [95%CI] = -0.5483 [-0.7305, -0.2933]) ( <a href="#fig-mal" class="quarto-xref">Figure&nbsp;6</a> ).</p>
<div id="fig-lg" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-lg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/lgsil.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-lg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Yearly screened women and LGSIL
</figcaption>
</figure>
</div>
<div id="fig-hg" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/hgsil.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hg-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Yearly screened women and HGSIL
</figcaption>
</figure>
</div>
<div id="fig-mal" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="fig/inv.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Yearly screened women and suspected invasive lesions
</figcaption>
</figure>
</div>
</section>
<section id="discussion" class="level1">
<h1>Discussion</h1>
<section id="key-results" class="level2">
<h2 class="anchored" data-anchor-id="key-results">Key results</h2>
<p>By analyzing routinely collected healthcare data from 95,120 satisfactory cervical smears records in the ECDU, this study reported the trends in screening uptake and in the observed epithelial abnormalities. While a notable increase in annual screened women occurred from 1981 to 1992, it declined afterward. Women who engaged in sexual intercourse at a young age, and made the conscious decision to undergo routine cytological screening exhibited a higher probability of presenting with epithelial abnormalities.&nbsp;Furthermore, it was observed that these abnormalities were more prevalent among women who underwent the screening process at a relatively advanced age in comparison to their counterparts. The most common epithelial abnormality was LGSIL. The yearly utilization of cervical screening by cytology was positively associated with LGSIL and negatively associated with invasive lesions.</p>
<p>This discrepancy between the recommended cervical cancer screening guidelines and the actual clinical practice was identified in a recent systematic review. Only six of 11 countries across North America, Europe, and Asia-Pacific have implemented comprehensive population-based screening programs. <span class="citation" data-cites="Wang2022">[<a href="#ref-Wang2022" role="doc-biblioref">11</a>]</span> This observation highlights a potential gap between policy recommendations and real-world implementation of cervical cancer prevention strategies.</p>
<p>Current consensus does not recommend the initiation of cervical cancer screening before the age 21 years in immunocompetent females due to very low rate of cervical cancer among women ages 20 to 24 years (0.8 per 100,000). <span class="citation" data-cites="Hosier2021">[<a href="#ref-Hosier2021" role="doc-biblioref">12</a>]</span> In Egypt, there is a social tendency for early age at marriage, and the results of this study found epithelial abnormalities to be associated with earlier sexual activity. This might have implications for practice.</p>
<p>This study found a 5.44% prevalence of epithelial abnormalities in cervical smears. This aligns with reports from other Arab countries like Saudi Arabia (4.27%) <span class="citation" data-cites="AlKadri2015">[<a href="#ref-AlKadri2015" role="doc-biblioref">13</a>]</span>, Jordan (3.8%) <span class="citation" data-cites="Maraqa2017">[<a href="#ref-Maraqa2017" role="doc-biblioref">14</a>]</span>, United Arab Emirates (3.3%) <span class="citation" data-cites="AlEyd2012">[<a href="#ref-AlEyd2012" role="doc-biblioref">15</a>]</span>, and Kuwait (4.4%) <span class="citation" data-cites="Kapila2015">[<a href="#ref-Kapila2015" role="doc-biblioref">16</a>]</span>. This similarity might be related to shared cultural and religious factors. This prevalence in our study is much lower than reported in sub-Saharan Africa as reported in studies from Southwestern Nigeria (34.6%) <span class="citation" data-cites="Akinfolarin2017">[<a href="#ref-Akinfolarin2017" role="doc-biblioref">17</a>]</span> and Northwest Ethiopia (14.1%) <span class="citation" data-cites="Getinet2015">[<a href="#ref-Getinet2015" role="doc-biblioref">18</a>]</span>. Coexisting HIV infection in these regions is a potential explanation for the higher rates.</p>
<p>In the current study, the epithelial abnormalities were significantly higher in women with routine check-up when compared to symptomatic women. Other reports have not found such a significant difference. <span class="citation" data-cites="AlKadri2015">[<a href="#ref-AlKadri2015" role="doc-biblioref">13</a>]</span> This finding suggests that routine cervical cancer screening may be more effective in detecting pre-cancerous changes than relying solely on the presence of symptoms.</p>
<p>In an Age-stratified analysis of the distribution of cytological abnormalities, we found that the majority of abnormal cells were found among women older than 60 years, may be due to the limited organized screening programs in Egypt in younger women with accumulation of detected epithelial abnormalities over time.</p>
<p>Our results indicate that women with ASC had significantly older age than those with LSIL and younger age than HSIL, and glandular cells. LSIL and AGUS showed significant lower age than Malignant Squamous Cell Carcinoma, HSIL and adenocarcinoma cases. This was consistent with the findings of previously published results of ASC, LSIL, and HSIL having a peak incidence in the 30–39-year age group while AGUS peaked among individuals aged 40-49 years. Malignant lesions exhibited a further increase in incidence after the age of 50 years. The mean age of diagnosis for LSIL and HSIL was 34.7 and 37.7 years, respectively, while malignant lesions presented with a mean age of diagnosis at 51.8 years. <span class="citation" data-cites="Gupta2007">[<a href="#ref-Gupta2007" role="doc-biblioref">19</a>]</span> This might have implications for screening practice. <span class="citation" data-cites="Fontham2020">[<a href="#ref-Fontham2020" role="doc-biblioref">20</a>]</span></p>
<p>Over a 42-year period SIL abnormalities showed a decline in LSIL from 6.9% to 4.3% and HSIL from 1.2% to 0.13%. The relative frequency of preinvasive abnormalities (ASC, LSIL, and HSIL) started at approximately 10% in 1981 and dropped to 5% in 2022. While the observed decline appears reassuring, it does not necessarily reflect the direct effectiveness of a comprehensive preventive strategy. This is because the screening service in ECDU currently operates on an opportunistic basis rather than a structured, population-based approach.</p>
<p>The effectiveness of structured, population-based preventive strategies in reducing the incidence rates of preinvasive and invasive lesions of the cervix can not be overstated. <span class="citation" data-cites="Adegoke2012 Ueda2018 Pesola2019 Chauhan2020">[<a href="#ref-Adegoke2012" role="doc-biblioref">21</a>–<a href="#ref-Chauhan2020" role="doc-biblioref">24</a>]</span> Yet, in the vast majority of Low- and Middle-Income Countries (LMICs) including Egypt, researchers have indentified a diverse array of obstacles to the process of screening <span class="citation" data-cites="Petersen2022">[<a href="#ref-Petersen2022" role="doc-biblioref">25</a>]</span>&nbsp;Therefore, LMICs need a prompt and immediate execution of unambiguous regulations, which should be fortified by the ability of the healthcare system to put these regulations into action.&nbsp;We need widespread advocacy within the community and the dissemination of information, alongside the strengthening of policies that promote the well-being of women and ensure gender equality.</p>
</section>
<section id="strengths-and-limitations" class="level2">
<h2 class="anchored" data-anchor-id="strengths-and-limitations">Strengths and limitations</h2>
<p>The present study has notable strengths. This study is among the limited number of reports that scrutinize longitudinal patterns in the uptake of cervical cancer screening in a middle income country. It highlighted the vital role that reliable data collected during routine healthcare data can play in describing practice and identifying the potential challenges in accessing care. Our study included a large number of participants and spanned 42 years of practice. Another strength of this work is that all cytologic findings were assessed and confirmed by highly competent pathologists and documented in the electronic database, reducing the possibility of incorrect classification of screening results.</p>
<p>This dataset had some missing data in demographic characteristics of participants. This is expected for studies conducted in a developing country to review routinely collected healthcare data. All demographic data are self-reported by women, which is prone to recall bias. The process of screening for cervical cancer is characterized by opportunistic practices rather than organized efforts. This implies that the subset of women who undergo screening differs from those who do not, as the former group has successfully surmounted various obstacles such as financial constraints, social factors, cultural influences, and geographic limitations to avail themselves of screening services. There is also a lack of information relating to the source of referral (e.g.&nbsp;self-referred or provider referred) for screening. Finally, the change of terminology used over time may have some implications for the assigned category of abnormality observed.</p>
</section>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>The utilization of cervical cancer screening and burden of epithelial abnormalities among women in Egypt were highlighted by our findings.&nbsp;Our results provide insights for policy makers, shaping advanced testing or vaccination policies. The findings suggest a potential for national expansion and integration with universal health coverage. The findings clearly show the need for a population-based national program, if we are keen to meet World Health Organization’s 2030 targets for cervical cancer elimination.</p>
</section>
<section id="list-of-abbreviations" class="level1">
<h1>List of abbreviations</h1>
<p>ECDU: Early Cancer Detection Unit</p>
</section>
<section id="list-of-tables" class="level1">
<h1>List of tables</h1>
<p>Table 1 Demographic characteristics of women screened at ECDU, Ain Shams University, 1981– 2022</p>
<p>Table 2 Results of cervical cytology among women screened at ECDU, Ain Shams University, 1981– 2022</p>
</section>
<section id="list-of-figures" class="level1">
<h1>List of figures</h1>
<p>Figure 1 Temporal trend of the number of screened women by year at ECDU, Ain Shams University, 1981– 2022</p>
<p>Figure 2 Temporal trend of squamous intra-epithelial lesions by year among women screened at ECDU, Ain Shams University, 1981– 2022</p>
<p>Figure 3 Temporal trend of premalignant and malignant findings by year among women screened at ECDU, Ain Shams University, 1981– 2022</p>
<p>Figure 4 Yearly screened women and LGSIL</p>
<p>Figure 5 Yearly screened women and HGSIL</p>
<p>Figure 6 Yearly screened women and suspected invasive lesions</p>
</section>
<section id="declarations" class="level1">
<h1>Declarations</h1>
<section id="ethics-approval-and-consent-to-participate" class="level2">
<h2 class="anchored" data-anchor-id="ethics-approval-and-consent-to-participate">Ethics approval and consent to participate</h2>
<p>Not applicable.</p>
</section>
<section id="consent-for-publication" class="level2">
<h2 class="anchored" data-anchor-id="consent-for-publication">Consent for publication</h2>
<p>Not applicable.</p>
</section>
<section id="availability-of-data-and-materials" class="level2">
<h2 class="anchored" data-anchor-id="availability-of-data-and-materials">Availability of data and materials</h2>
<p>All data relevant to this study are publicly available. Data, analysis script and materials related to this study are publicly available on an open access registry. To facilitate reproducibility, this manuscript was written by interleaving regular prose and analysis code using R Markdown.</p>
</section>
<section id="competing-interests" class="level2">
<h2 class="anchored" data-anchor-id="competing-interests">Competing interests</h2>
<p>The authors declare that they have no competing interests.</p>
</section>
<section id="funding" class="level2">
<h2 class="anchored" data-anchor-id="funding">Funding</h2>
<p>This research received no specific grant from any funding agency in the public, commercial or not-for-profit sectors.</p>
</section>
<section id="authors-contributions" class="level2">
<h2 class="anchored" data-anchor-id="authors-contributions">Authors’ contributions</h2>
<p>All authors collaborated in conceiving the idea for this study and in conducting the work. SE and AN contributed to data analysis and interpretation of the results. SE, AN, RA wrote the first draft of the manuscript. All authors revised the manuscript critically for important intellectual content. All authors approved the final version of the manuscript. SE is the guarantor for the dataset and for the final manuscript.</p>
</section>
<section id="acknowledgements" class="level2">
<h2 class="anchored" data-anchor-id="acknowledgements">Acknowledgements</h2>
<p>Early Cervical Cancer Detection Collaborators: Sorted alphabet</p>
<p>Maya Abdelrazek, Magda Abdelsalam, Reem Abdelsalam, Rehab Abdelrahman, Radwa Ali, Amal Alloub, Hamdy Alqenawy, Nahla Awad, Sohair Ayaad, Hala El-Sallaly, Amro Elhusseiny, Sahar Ezzelarab, Ragia Fahmy, Asmaa Kasem, Ghada Moubarak, Ashraf Nabhan, Magda Nasreldin, Ragaa Rifaat, Zeinab Shehabeldin, Ahmed Zenhom</p>
</section>
</section>
<section id="references" class="level1 unnumbered">


</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body" role="list">
<div id="ref-ferlay2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Ferlay J, Ervik M, Lam F, Colombet M, Mery L, Piñeros M, et al. Global cancer observatory: Cancer today. [Internet]. Lyon, France: International Agency for Research on Cancer; 2020. Available from: <a href="https://gco.iarc.fr/today/online-analysis-map">https://gco.iarc.fr/today/online-analysis-map</a></div>
</div>
<div id="ref-Schiffman2016" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">Schiffman M, Doorbar J, Wentzensen N, Sanjosé S de, Fakhry C, Monk BJ, et al. <a href="https://doi.org/10.1038/nrdp.2016.86">Carcinogenic human papillomavirus infection</a>. Nature Reviews Disease Primers. 2016 Dec;2(1):16086. </div>
</div>
<div id="ref-Wright2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">Wright J. Cervical intraepithelial neoplasia: Terminology, incidence, pathogenesis, and prevention [Internet]. Barbieri R, editor. Wolters Kluwer; 2023. Available from: <a href="https://www.uptodate.com/contents/cervical-intraepithelial-neoplasia-terminology-incidence-pathogenesis-and-prevention#references">https://www.uptodate.com/contents/cervical-intraepithelial-neoplasia-terminology-incidence-pathogenesis-and-prevention#references</a></div>
</div>
<div id="ref-Bouvard2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">Bouvard V, Wentzensen N, Mackie A, Berkhof J, Brotherton J, Giorgi-Rossi P, et al. <a href="https://doi.org/10.1056/NEJMsr2030640">The IARC perspective on cervical cancer screening</a>. New England Journal of Medicine. 2021;385(20):1908–18. </div>
</div>
<div id="ref-WHO2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline"><a href="https://www.ncbi.nlm.nih.gov/pubmed/34314129">WHO guideline for screening and treatment of cervical pre-cancer lesions for cervical cancer prevention</a>. Second Edition. Geneva: World Health Organization; 2021. 1197 p. </div>
</div>
<div id="ref-wh2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">World Health Organization. Global strategy to accelerate the elimination of cervical cancer as a public health problem [Internet]. Geneva: World Health Organization; 2020. Available from: <a href="https://iris.who.int/handle/10665/336583">https://iris.who.int/handle/10665/336583</a></div>
</div>
<div id="ref-Gakidou2008" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Gakidou E, Nordhagen S, Obermeyer Z. <a href="https://doi.org/10.1371/journal.pmed.0050132">Coverage of cervical cancer screening in 57 countries: Low average levels and large inequalities.</a> PLoS medicine. 2008 Jun;5:e132. </div>
</div>
<div id="ref-Peirson2013" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Peirson L, Fitzpatrick-Lewis D, Ciliska D, Warren R. <a href="https://doi.org/10.1186/2046-4053-2-35">Screening for cervical cancer: A systematic review and meta-analysis</a>. Systematic Reviews. 2013;2(1):35. </div>
</div>
<div id="ref-Perkins2023" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Perkins RB, Wentzensen N, Guido RS, Schiffman M. <a href="https://doi.org/10.1001/jama.2023.13174">Cervical cancer screening: A review</a>. JAMA. 2023 Aug;330(6):547. </div>
</div>
<div id="ref-Health2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Egypt health issues survey 2015 [Internet]. Cairo, Egypt: Ministry of Health; Population, Egypt; ICF International; 2015. Available from: <a href="http://dhsprogram.com/pubs/pdf/FR313/FR313.pdf">http://dhsprogram.com/pubs/pdf/FR313/FR313.pdf</a></div>
</div>
<div id="ref-Wang2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">11. </div><div class="csl-right-inline">Wang W, Arcà E, Sinha A, Hartl K, Houwing N, Kothari S. <a href="https://doi.org/10.1016/j.pmedr.2022.101813">Cervical cancer screening guidelines and screening practices in 11 countries: A systematic literature review</a>. Preventive Medicine Reports. 2022;28:101813. </div>
</div>
<div id="ref-Hosier2021" class="csl-entry" role="listitem">
<div class="csl-left-margin">12. </div><div class="csl-right-inline">Hosier H, Sheth SS, Oliveira CR, Perley LE, Vash-Margita A. <a href="https://doi.org/10.1016/j.ajog.2021.07.005">Unindicated cervical cancer screening in adolescent females within a large healthcare system in the united states</a>. American Journal of Obstetrics and Gynecology. 2021;225(6):649.e1–9. </div>
</div>
<div id="ref-AlKadri2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">13. </div><div class="csl-right-inline">Al-Kadri HM, Kamal M, Bamuhair SS, Omair AA, Bamefleh HS. <a href="https://doi.org/10.15537/smj.2015.1.9141">Prevalence and characteristics of abnormal papanicolaou smear in central saudi arabia</a>. Saudi Medical Journal. 2015;36(1):117–22. </div>
</div>
<div id="ref-Maraqa2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">14. </div><div class="csl-right-inline">Maraqa B, Lataifeh I, Ottai L, Badran O, Nouri YQ, Issam I, et al. <a href="https://doi.org/10.22034/APJCP.2017.18.11.3117">Prevalence of abnormal pap smears: A descriptive study from a cancer center in a low-prevalence community</a>. Asian Pacific Journal of Cancer Prevention. 2017 Nov;18(11, 11):3117–21. </div>
</div>
<div id="ref-AlEyd2012" class="csl-entry" role="listitem">
<div class="csl-left-margin">15. </div><div class="csl-right-inline">Al Eyd GJ, Shaik RB. <a href="https://doi.org/10.12816/0003173">Rate of opportunistic pap smear screening and patterns of epithelial cell abnormalities in pap smears among women attending a teaching hospital in ajman , united arab emirates</a>. Sultan Qaboos University Medical Journal. 2012;12(4):473–8. </div>
</div>
<div id="ref-Kapila2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">16. </div><div class="csl-right-inline">Kapila K, Sharma PN, George SS, Al-Shaheen A, Al-Juwaiser A, Al-Awadhi R. Trends in epithelial cell abnormalities observed on cervical smears over a 21-year period in a tertiary care hospital in kuwait. Sultan Qaboos University Medical Journal. 2015;15(1):e112–115. </div>
</div>
<div id="ref-Akinfolarin2017" class="csl-entry" role="listitem">
<div class="csl-left-margin">17. </div><div class="csl-right-inline">Akinfolarin A, Olusegun A, Omoladun O, Omoniyi-Esan G, Onwundiegu U. <a href="https://doi.org/10.4103/JOC.JOC_199_15">Age and pattern of pap smear abnormalities: Implications for cervical cancer control in a developing country</a>. Journal of Cytology. 2017;34(4):208. </div>
</div>
<div id="ref-Getinet2015" class="csl-entry" role="listitem">
<div class="csl-left-margin">18. </div><div class="csl-right-inline">Getinet M, Gelaw B, Sisay A, Mahmoud EA, Assefa A. <a href="https://doi.org/10.1186/s12907-015-0016-2">Prevalence and predictors of pap smear cervical epithelial cell abnormality among HIV-positive and negative women attending gynecological examination in cervical cancer screening center at debre markos referral hospital, east gojjam, northwest ethiopia</a>. BMC Clinical Pathology. 2015;15(1):16. </div>
</div>
<div id="ref-Gupta2007" class="csl-entry" role="listitem">
<div class="csl-left-margin">19. </div><div class="csl-right-inline">Gupta S, Sodhani P, Halder K, Chachra KL, Sardana S, Singh V, et al. <a href="https://doi.org/10.1016/j.ejogrb.2006.07.022">Spectrum of epithelial cell abnormalities of uterine cervix in a cervical cancer screening programme: Implications for resource limited settings</a>. European Journal of Obstetrics &amp; Gynecology and Reproductive Biology. 2007;134(2):238–42. </div>
</div>
<div id="ref-Fontham2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">20. </div><div class="csl-right-inline">Fontham ETH, Wolf AMD, Church TR, Etzioni R, Flowers CR, Herzig A, et al. <a href="https://doi.org/10.3322/caac.21628">Cervical cancer screening for individuals at average risk: 2020 guideline update from the american cancer society</a>. CA: A Cancer Journal for Clinicians. 2020;70(5):321–46. </div>
</div>
<div id="ref-Adegoke2012" class="csl-entry" role="listitem">
<div class="csl-left-margin">21. </div><div class="csl-right-inline">Adegoke O, Kulasingam S, Virnig B. <a href="https://doi.org/10.1089/jwh.2011.3385">Cervical cancer trends in the united states: A 35-year population-based analysis</a>. Journal of Women’s Health. 2012;21(10):1031–7. </div>
</div>
<div id="ref-Ueda2018" class="csl-entry" role="listitem">
<div class="csl-left-margin">22. </div><div class="csl-right-inline">Ueda Y, Yagi A, Nakayama T, Hirai K, Ikeda S, Sekine M, et al. <a href="https://doi.org/10.1038/s41598-018-23947-6">Dynamic changes in japan’s prevalence of abnormal findings in cervical cytology depending on birth year</a>. Scientific Reports. 2018;8(1):5612. </div>
</div>
<div id="ref-Pesola2019" class="csl-entry" role="listitem">
<div class="csl-left-margin">23. </div><div class="csl-right-inline">Pesola F, Sasieni P. <a href="https://doi.org/10.1136/bmjopen-2018-026292">Impact of screening on cervical cancer incidence in england: A time trend analysis</a>. BMJ Open. 2019;9(1):e026292. </div>
</div>
<div id="ref-Chauhan2020" class="csl-entry" role="listitem">
<div class="csl-left-margin">24. </div><div class="csl-right-inline">Chauhan AS, Prinja S, Srinivasan R, Rai B, Malliga J, Jyani G, et al. <a href="https://doi.org/10.1371/journal.pone.0238291">Cost effectiveness of strategies for cervical cancer prevention in india</a>. PLOS ONE. 2020;15(9):e0238291. </div>
</div>
<div id="ref-Petersen2022" class="csl-entry" role="listitem">
<div class="csl-left-margin">25. </div><div class="csl-right-inline">Petersen Z, Jaca A, Ginindza TG, Maseko G, Takatshana S, Ndlovu P, et al. <a href="https://doi.org/10.1186/s12905-022-02043-y">Barriers to uptake of cervical cancer screening services in low-and-middle-income countries: A systematic review.</a> BMC women’s health. 2022 Dec;22:486. </div>
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>